### ISSUE TITLE
Obtain certificates fro backup email server (MX) 

### ISSUE THREAD

**Issue by danjde** [gheja/dns-01-manual#1]
Hi gheia!
I don't know if you want to help me (a little) for understand better how to obtaining certificates for a backup email server using dns-01 challenge method.
Could I ask you some clarification on the use of your method?

many thanks

Davide
Italy

**Comment by gheja** [comment]
Hi danjde!

I think you need to generate the private key and the certificate signing request on the backup email server and then download the [dehydrated script](https://github.com/lukas2511/dehydrated) and the hook.sh from this repository  to the backup email server. Then run:

` /path/to/dehydrated --challenge dns-01 --hook /path/to/hook.sh --signcsr /path/to/csr.pem
`

This will show you something like:

> Add the following to the zone definition of example.com:
> _acme-challenge.example.com. IN TXT "aaabbbcccddeeefffgghhh"
> 
> Press enter to continue...
> 

Thenk add the TXT record to your zone on your master name server and press enter on the backup email server. After that the verification should be complete and you can safely remove that TXT record.

I hope this helps.

Gabor

**Comment by danjde** [comment]
Hi Gabor, and thanks for your kind help!!
Now I've decided to change approach, the challenge dns-01 method is too complicated to automatize.

Now I'm oriented here: https://community.letsencrypt.org/t/will-lets-encrypt-work-for-me-multiple-servers-serving-one-domain/6830/17

I'm trying... :-)

ciao!
